name: CI

on:
  push:
    branches: 
      - main
      - dev2
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
jobs:
  build_and_test_20_Z04:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          echo building project
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6
          
  build_and_test_18_04:
    runs-on:  	ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          echo building project
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6
name: Send mail
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 465
    subject: Github Actions job result
    to: dome.dev0@gmail.com
    from: C_Lab_Proj
    secure: true
    body: "Build job of ${{github.repository}} completed with status: ${{ job.status }}"
    ignore_cert: true
    priority: normal