name: CI

on:
  push:
    branches: 
      - main
      - dev2
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
jobs:
  build_and_test_20_04:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project - ubuntu-latest
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler input_output_results/ps input_output_results/ps2 input_output_results/ps3 input_output_results/ps4 input_output_results/ps5 ps6 input_output_results/ps7
          echo compare input_output_results/ps.ob input_output_results/main_tester
          cmp input_output_results/ps.ob input_output_results/main_tester.ob
      - uses: actions/upload-artifact@v3
        with:
          name: assembler.zip
          path: |
            misc
            passes
            input_output_results 
            assembler
            assembler.c
            Makefile
          
  build_and_test_18_04:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: build project - ubuntu-18.04
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler input_output_results/ps input_output_results/ps2 input_output_results/ps3 input_output_results/ps4 input_output_results/ps5 ps6 input_output_results/ps7
          echo compare input_output_results/ps.ob input_output_results/main_tester
          cmp input_output_results/ps.ob input_output_results/main_tester.ob

  build_and_test_macos-latest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project - macos-latest
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler input_output_results/ps input_output_results/ps2 input_output_results/ps3 input_output_results/ps4 input_output_results/ps5 ps6 input_output_results/ps7
