name: CI

on:
  push:
    branches: 
      - main
      - dev2
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
jobs:
  build_and_test_20_04:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          echo building project
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6
          
  build_and_test_18_04:
    runs-on:  	ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: build project
        run: |
          echo building project
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6
