name: CI

on:
  push:
    branches: 
      - main
      - dev2
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'
jobs:
  build_and_test_20_04:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project - ubuntu-latest
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6 ps7
          echo compare tester/ps.ob tester/main_tester
          cmp tester/ps.ob tester/main_tester
          
  build_and_test_18_04:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: build project - ubuntu-18.04
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6 ps7
          echo compare tester/ps.ob tester/main_tester
          cmp tester/ps.ob tester/main_tester

  build_and_test_macos-latest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: build project - macos-latest
        run: |
          echo building project
          rm -f assembler
          make
          ./assembler ps ps2 ps3 ps4 ps5 ps6 ps7